import 'dart:convert';
import 'package:http/http.dart' as http;
import 'package:untitled2/src/model/model_data_api.dart';

class AllData {
  AutogeneratedData data;

  Future<AutogeneratedData> fetchDataFromAPI() async {
    final response = await http.get('http://p-prent.com/api/fmeb');

    if (response.statusCode == 200) {
      // If the server did return a 200 OK response,
      // then parse the JSON.

      data = AutogeneratedData.fromJson(jsonDecode(response.body));

      // print(data.toString());
      return data;
    } else {
      // If the server did not return a 200 OK response,
      // then throw an exception.
      throw Exception('Failed to load data');
    }
  }
}
