const Map<String, String> ar = {
  "search for favorite product": "ابحث عن طابعتك المفضلة",
  "Size": "حجم الطابعة",
  "prints canon": "Canon طابعات",
  "prints Richo": "Richo طابعات",
  "prints hp": "Hp طابعات",
  "more": "المزيد",
  "description": "الوصف",
  "size print": "حجم الطابعة",
  "chick time": "عدد مرات اختبار الطابعة",
  "features": "اهم مميزات الكابعه",
  "home main": "الصفحة الرئيسية",
  "cart": "السلة",
  "favorite": "المفضلة",
  "web side": "موقعنا",
  "about us": "عننا",
  "buy print": "اشتري طابعتك",
  "search for your print": "ابحث عن طابعتك",
  "add to cart": "اضف الي السلة",
  "good choice": "اختيار رائع",
  "are you sure added this print": "هل انت متاكد من اضافة هذه الطابعة",
  "are you sure buy this print": "هل انت متاكد من شراء هذه الطابعة",
  "add": "اضافة",
  "changed my mind": "غيرت رايي",
  "changed my mind again": "غيرت رايي تاني",
  "success to add print to cart": "تمت اضافة بنجاح الي السلة",
  "success to add print to favorite": "تمت اضافة بنجاح الي المفضلة",
  "type of print": "نوع الطابعة",
  "size of print": "حجم الطابعة",
  "remove from cart": "ازالة من السلة",
  "remove from favorite": "ازالة من المفضلة",
  "buy": "شراء الطابعة",
  "order print": "الطلب الان",
  "complete application": "مليء الاستمارة",
  "enter your name": "ادخل اسمك بالكامل",
  "enter your phone": "ادخل رقم الموبيل",
  "enter your phone whats app": "ادخل رقم الواتس",
  "enter your address": "ادخل العنوان",
  "send order": "ارسال الطلب",
  "send": "ارسال",
  "sure you naw": "انت اكيد عرفت",
  "can't be empty": "املي هذه الخانة",
  "success to send order": "تم ارسال الطلب بنجاح",
  "You will be contacted within a day":"سيتم التواصل معكم خلال يوم",
  "cancel":"لا يسيدي شكرا",
  "yes i agree":"ايوة موافق"
};
