const Map<String, String> en = {
  "search for favorite product": "search for favorite product",
  "Size": "Size",
  "prints canon": "Canon طابعات",
  "prints Richo": "Richo طابعات",
  "prints hp": "Hp طابعات",
  "more": "more",
  "description": "description",
  "size print": "size print",
  "chick time": "chick time",
  "features": "features",
  "home main": "home main",
  "cart": "cart",
  "favorite": "favorite",
  "web side": "web side",
  "about us": "about us",
  "buy print": "buy print",
  "search for your print": "search for your print",
  "add to cart": "add to cart",
  "good choice": "good choice",
  "are you sure added this print": "are you sure added this print",
  "are you sure buy this print": "are you sure buy this print",
  "add": "add",
  "changed my mind": "changed my mind",
  "changed my mind again": "changed my mind again",
  "success to add print to cart": "success to add print to cart",
  "success to add print to favorite": "success to add print to favorite",
  "type of print": "type of print",
  "size of print": "size of print",
  "remove from cart": "remove from cart",
  "buy": "buy",
  "order print": "order print",
  "complete application": "complete application",
  "enter your name": "enter your name",
  "enter your phone": "enter your phone",
  "enter your phone whats app": "enter your phone whats app",
  "enter your address": "enter your address",
  "send order": "send order",
  "send": "send",
  "sure you naw": "sure you naw",
  "can't be empty": "can't be empty",
  "success to send order": "success to send order",
  "You will be contacted within a day": "You will be contacted within a day",
  "cancel": "Cancel",
  "yes i agree": "yes i agree"
};
